/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Cart.java
 *
 * Created on Nov 28, 2011, 1:15:55 AM
 */
package javashop.client;

import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author quanmt
 */
public class Cart extends javax.swing.JFrame {

    Product product = new Product();
    
    Vector vColumn = new Vector();
    Vector vData = new Vector();

    DefaultTableModel tableModel = new DefaultTableModel(vData, vColumn);
    
    /** Creates new form Cart */
    public Cart() {
        
        // table column
        vColumn.add("Product ID");
        vColumn.add("Product Name");
        vColumn.add("Quantity");
        
        // add test data
        //addAllProductsToCart();
        
        initComponents();
        updateCart();
        
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    public void addAllProductsToCart() {
        Order order = App.getOrder();
        
        Vector<Product> products = this.product.getListByCategory(null);
        for(int i = 0; i < products.size(); i++) {
            Product currentProduct = products.get(i);
            order.addCart(currentProduct, 2);
        }
    }
    
    /**
     * Clear all rows
     */
    public void clearTable() {
        while(this.tableModel.getRowCount() > 0) {
            this.tableModel.removeRow(0);
        }
    }
    
    /**
     * Update cart
     */
    public void updateCart() {
        Order order = App.getOrder();
        
        this.clearTable();
        Vector<javashop.entity.OrderProduct> orderProducts = order.getOrderProducts();
        for (int i = 0; i < orderProducts.size(); i++) {
            Vector row = new Vector();
            OrderProduct orderProduct = (OrderProduct) orderProducts.get(i);
            row.add(orderProduct.getProduct().getId());
            row.add(orderProduct.getProduct().getName());
            row.add(orderProduct.getQuantity());
            this.tableModel.addRow(row);
        }
        
        this.totalAmountLabel.setText(String.valueOf(order.getTotalAmount()));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        continueButton = new javax.swing.JButton();
        checkoutButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        totalAmountLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Shopping Cart");

        orderTable.setModel(this.tableModel);
        jScrollPane1.setViewportView(orderTable);

        continueButton.setText("Continue Shopping");
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });

        checkoutButton.setText("Checkout");
        checkoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Total:");

        totalAmountLabel.setText("0");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(continueButton)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(updateButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 113, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(checkoutButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jLabel1)
                        .add(18, 18, 18)
                        .add(totalAmountLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 167, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 338, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(totalAmountLabel)
                    .add(jLabel1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 24, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(checkoutButton)
                    .add(continueButton)
                    .add(updateButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
        this.dispose();
        ListProducts listProducts = new ListProducts();
        listProducts.setVisible(true);
    }//GEN-LAST:event_continueButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        Vector<javashop.entity.OrderProduct> orderProducts = App.getOrder().getOrderProducts();
        
        for (int i = 0; i < this.tableModel.getRowCount(); i++) {
            int quantity = Integer.valueOf(this.orderTable.getValueAt(i, 2).toString());
            orderProducts.get(i).setQuantity(quantity);
        }
        
        this.updateCart();
    }//GEN-LAST:event_updateButtonActionPerformed

    private void checkoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutButtonActionPerformed
        if (App.getUser() == null) {
            JOptionPane.showMessageDialog(this, "You have to be logged in first");
            Users users = new Users();
            users.setVisible(true);
            return;
        }
        App.getOrder().add();
        
        JOptionPane.showMessageDialog(this, "Your order has been saved!");
        App.setOrder(null);
        this.updateCart();
    }//GEN-LAST:event_checkoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Cart().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkoutButton;
    private javax.swing.JButton continueButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable orderTable;
    private javax.swing.JLabel totalAmountLabel;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
